
server:
  port: 8088
  
  
spring:
  application:
    name: Congfig-server
  profiles:
    active: native
    
      
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: "http://localhost:8761/eureka"
